Provide a default for `create_comment` (#314)
The action definition is missing the default value for `create_comment`, so even though is marked as optional, it is currently required.

If it is not specified, the action errors out when it should report an error:
```
Error: Input does not meet YAML 1.2 "Core Schema" specification: create_comment
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```